# Generated by Django 3.0.8 on 2020-07-22 17:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('blog', '0003_auto_20200722_1736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPostPage',
            new_name='BlogPage',
        ),
    ]
